import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  modalContainer: {
    alignItems: 'center',
    position: 'relative',
  },
  iconWrapper: {
    alignSelf: 'center',
    position: 'absolute',
    top: -43,
    left: 0,
    right: 0,
    zIndex: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.16,
    shadowRadius: 11,
    elevation: 4,
  },
  iconImage: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    borderRadius: 40,
    borderWidth: 10,
    borderColor: '#fff',
    backgroundColor: '#fff',
    elevation: 2,
  },
  modalContentBox: {
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingTop: 40,
    paddingBottom: 32,
    paddingHorizontal: 32,
    alignItems: 'center',
    width: 330,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.11,
    shadowRadius: 18,
  },
  modalTitle: {
    fontSize: 22,
    color: '#202020',
    textAlign: 'center',
    marginBottom: 9,
    letterSpacing: -0.2,
    fontFamily: 'Raleway',
  },
  modalText: {
    fontSize: 14,
    color: '#202020',
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 25,
    fontFamily: 'Nunito-Sans-Regular',
    letterSpacing: -0.08,
  },
  buttonsOuterWrap: {
    width: '100%',
    alignItems: 'center',
  },
  primaryButton: {
    backgroundColor: '#E7E8EB',
    borderRadius: 11,
    paddingVertical: 12,
    paddingHorizontal: 21,
    alignItems: 'center',
    minWidth: 120,
    minHeight: 40,
    flex: 1,
    marginHorizontal: 5,
    marginBottom: 15,
  },
  buttonText: {
    color: '#202020',
    fontSize: 13,
    fontFamily: 'NunitoSans-Regular',
  },
});
