import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  modalContainer: {
    alignItems: 'center',
    position: 'relative',
  },

  iconWrapper: {
    alignSelf: 'center',
    position: 'absolute',
    top: -38,
    left: 0,
    right: 0,
    zIndex: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.1608,
    shadowRadius: 11,
    elevation: 3,
  },
  iconImage: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    borderRadius: 40,
    borderWidth: 6,
    borderColor: '#fff',
    elevation: 2,
    backgroundColor: '#fff',
  },

  modalContentBox: {
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingTop: 45,
    paddingBottom: 32,
    paddingHorizontal: 32,
    alignItems: 'center',
    width: 330,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.11,
    shadowRadius: 18,
  },
  modalTitle: {
    fontSize: 22,
    color: '#202020',
    textAlign: 'center',
    marginBottom: 9,
    letterSpacing: -0.2,
    fontFamily: 'Raleway',
  },
  modalText: {
    fontSize: 12,
    color: '#202020',
    textAlign: 'center',
    marginBottom: 25,
    lineHeight: 25,
    fontFamily: 'Nunito-Sans-Regular',
    letterSpacing: -0.08,
  },
  buttonsOuterWrap: {
    width: '100%',
    alignItems: 'center',
  },
  buttonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 8,
    justifyContent: 'space-between',
  },
  primaryButton: {
    backgroundColor: '#202020',
    borderRadius: 11,
    paddingVertical: 12,
    paddingHorizontal: 21,
    alignItems: 'center',
    minWidth: 120,
    minHeight: 30,
    marginHorizontal: 5,
  },
  secondaryButton: {
    backgroundColor: '#ededed',
    borderRadius: 11,
    paddingVertical: 12,
    paddingHorizontal: 21,
    alignItems: 'center',
    minWidth: 120,
    minHeight: 30,
    marginHorizontal: 5,
  },
  buttonHalfWidth: {
    flex: 1,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'NunitoSans-Regular',
    fontWeight: '500',
    textAlign: 'center',
    letterSpacing: 0,
  },
  secondaryButtonText: {
    color: '#202020',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  star: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  imageStar: {
    height: 40,
    width: 40,
    marginRight: 10,
  },
  cancelButton: {
    backgroundColor: '#202020',
    borderRadius: 11,
    paddingVertical: 12,
    paddingHorizontal: 32,
    alignItems: 'center',
    minWidth: 120,
    minHeight: 47,
    flex: 1,
    marginHorizontal: 5,
  },
  cancelButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'NunitoSans-Regular',
    fontWeight: '500',
    textAlign: 'center',
    letterSpacing: 0,
  },
  deleteButton: {
    backgroundColor: '#ED7F7F', // red
    borderRadius: 11,
    paddingVertical: 12,
    paddingHorizontal: 32,
    alignItems: 'center',
    minWidth: 120,
    minHeight: 47,
    flex: 1,
    marginHorizontal: 5,
  },
  deleteButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'NunitoSans-Regular',
    fontWeight: '500',
    textAlign: 'center',
    letterSpacing: 0,
  },
});
