export type RootStackParamList = {
  Start: undefined;
  CreateAccount: undefined;
  Login: undefined;
  Password: undefined;
  PasswordRecovery: undefined;
  PasswordRecoveryCode: undefined;
  NewPassword: undefined;
  HelloCard: undefined;
  ReadyCard: undefined;
  Profile: undefined;
  BottomTabNavigator: undefined;
  CategoriesFilter: undefined;
  ShopSearch: undefined;
  ShopFilter: undefined;
  ShopReviews: undefined;
  ProductVariations: undefined;
  Reviews: undefined;
  ShopClothing: {
    id?: number;
    category: string;
  };
  Product: { id: string };
  Wishlist: undefined;
  WishlistEmpty: undefined;
  WishlistRecentlyViewed: undefined;
  CartPayment: undefined;
  ProfileToReceive: undefined;
  ProfileToReceiveProgress: undefined;
  ProfileHistory: undefined;
  ProfileVoucher: undefined;
  Settings: undefined;
  SettingsProfile: undefined;
  SettingsPaymentMethod: undefined;
  SettingsShippingAddress: undefined;
  SettingsCountry: undefined;
  SettingsLanguage: undefined;
  SettingsCurrency: undefined;
  SettingsSizes: undefined;
  About: undefined;
};
