import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  modalContainer: {
    alignItems: 'center',
    position: 'relative',
  },
  exclamationWrapper: {
    position: 'absolute',
    top: -55,
    alignSelf: 'center',
    zIndex: 10,
  },
  circleOuter: {
    width: 100,
    height: 100,
    borderRadius: 60,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  circleMiddle: {
    width: 65,
    height: 65,
    borderRadius: 42.5,
    backgroundColor: '#ffe6e6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleInner: {
    width: 30,
    height: 30,
    borderRadius: 29,
    backgroundColor: '#ffb3ba',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  exclamationText: {
    fontSize: 28,
    color: '#fff',
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 30,
  },
  modalContentBox: {
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingTop: 65,
    paddingBottom: 30,
    paddingHorizontal: 35,
    alignItems: 'center',
    width: 360,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
  },
  modalText: {
    fontSize: 18,
    color: 'black',
    textAlign: 'center',
    marginBottom: 35,
    fontWeight: '400',
    lineHeight: 26,
    fontFamily: 'Raleway',
    letterSpacing: -0.18,
  },
  okayButton: {
    backgroundColor: '#202020',
    borderRadius: 19,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    minWidth: 201,
    minHeight: 50,
  },
  okayButtonText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Nunito Sans',
    fontWeight: '300',
    lineHeight: 31,
    letterSpacing: 0,
  },
});
