import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    alignItems: 'center',
  },
  left: {
    position: 'relative',
    width: 112,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  imageWrapper: {
    width: 130,
    height: 114,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1608,
    shadowRadius: 10,
    elevation: 4,
  },

  productImage: {
    width: '100%',
    height: '100%',
    borderRadius: 9,
    resizeMode: 'cover',
  },
  deleteButton: {
    position: 'absolute',
    left: 5,
    bottom: 5,
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    shadowOpacity: 0.1608,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 4 },
    shadowColor: '#222',
  },

  deleteIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  middle: {
    flex: 1,
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 13,
    marginLeft: 12,
  },
  subtext: {
    fontSize: 14,
    color: '#222',
    marginBottom: 4,
    fontFamily: 'Nunito-Sans-Regular',
    lineHeight: 16,
    letterSpacing: 0,
  },
  subtext1: {
    fontSize: 16,
    color: '#222',
    marginBottom: 4,
    fontFamily: 'Nunito-Sans-Regular',
    lineHeight: 16,
    letterSpacing: 0,
    marginTop: 10,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 20,
    justifyContent: 'space-between',
  },
  discountedPrice: {
    fontSize: 20,
    color: '#df4183',
    textDecorationLine: 'line-through',
    fontFamily: 'Raleway',
    marginRight: 8,
    opacity: 0.56,
  },
  price: {
    fontSize: 18,
    color: '#202020',
    marginRight: 8,
    fontFamily: 'Raleway',
    lineHeight: 22,
    letterSpacing: -0.18,
  },
  controls: {
    flexDirection: 'row',
    marginTop: 1,
  },
  button: {
    width: 30,
    height: 30,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: '#2961f5',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 8,
    backgroundColor: 'white',
  },
  buttonText: {
    fontSize: 16,
    color: '#2961f5',
    textAlign: 'center',
    fontFamily: 'Nunito-Sans-Regular',
  },
  quantityBox: {
    backgroundColor: '#EEF2FF',
    width: 45,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityText: {
    fontSize: 16,
    color: '#1a2257',
    fontFamily: 'Raleway',
  },
});
