import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginVertical: 16,
    color: '#111',
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 15,
  },
  tabBtn: {
    paddingVertical: 8,
    paddingHorizontal: 37,
    borderRadius: 10,
    backgroundColor: '#F9F9F9',
  },
  activeTabBtn: {
    backgroundColor: '#e5eeff',
    borderWidth: 1,
    borderColor: '#004CFF',
  },
  tabText: {
    fontSize: 14,
    color: '#111',
    fontWeight: '500',
  },
  activeTabText: {
    color: '#004CFF',
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 5,
    marginBottom: 10,
    shadowColor: '#222',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.102,
    shadowRadius: 4,
  },
  icon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    marginRight: 12,
  },
  arrow: {
    marginRight: 10,
  },
  arrowCircle: {
    backgroundColor: '#0F4BFF',
    borderRadius: 20,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 135,
  },
  arrowText: {
    color: '#ffffff',
    fontSize: 19,
  },
  catLabel: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    color: '#202020',
    fontFamily: 'Raleway',
    lineHeight: 21,
    letterSpacing: -0.17,
  },
  justForYou: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f9ff',
    padding: 16,
    borderRadius: 16,
    marginTop: 20,
    marginBottom: 60,
    shadowColor: '#c0cfff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  justText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#222',
    marginLeft: 8,
  },
  star: {
    fontSize: 18,
    color: '#2869ff',
    marginLeft: 4,
  },
  rightArrow: {
    marginLeft: 'auto',
    backgroundColor: '#2869ff',
    borderRadius: 100,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
