import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  modalContainer: {
    alignItems: 'center',
    position: 'relative',
  },
  iconWrapper: {
    alignSelf: 'center',
    position: 'absolute',
    top: -43,
    left: 0,
    right: 0,
    zIndex: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.1608,
    shadowRadius: 11,
  },
  iconImage: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    borderRadius: 40,
    borderWidth: 6,
    borderColor: '#fff',
    backgroundColor: '#fff',
  },
  modalContentBox: {
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingTop: 60,
    paddingBottom: 32,
    paddingHorizontal: 32,
    alignItems: 'center',
    width: 330,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.11,
    shadowRadius: 18,
  },
  modalTitle: {
    fontSize: 22,
    color: '#202020',
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 9,
    letterSpacing: -0.2,
    fontFamily: 'Raleway',
  },
  modalText: {
    fontSize: 17,
    color: '#202020',
    textAlign: 'center',
    marginBottom: 38,
    fontWeight: '400',
    lineHeight: 25,
    fontFamily: 'Raleway',
    letterSpacing: -0.08,
  },
});
