import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginVertical: 24,
  },
  track: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 12,
    backgroundColor: '#e7eafd',
    borderRadius: 6,
    paddingVertical: 10,
    zIndex: -2,
  },
  progressFill: {
    position: 'absolute',
    left: 0,
    height: 12,
    backgroundColor: '#004CFF',
    borderRadius: 6,
    zIndex: 1,
    marginLeft: 5,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderColor: '#FFFFFF',
  },
  circleWrapper: {
    position: 'absolute',
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'space-around',
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1608,
    shadowRadius: 2,
    backgroundColor: 'transparent',
  },
  circleOuter: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 4,
    borderColor: '#e7eafd',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleActive: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#004CFF',
    borderWidth: 5,
    borderColor: '#fff',
  },
  circleInactive: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#fff',
    borderWidth: 5,
    borderColor: '#fff',
  },
});
